### ISSUE TITLE
windwos 10 

### ISSUE THREAD

**Issue by karborator** [databilim/rtsp-stream#3]
```
$ node app.js
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-rtsp_transport',
    'tcp',
    '-i',
    'rtsp://admin:123456@213.145.105.147:554/ch01.264',
    '-f',
    'mpeg1video',
    '-b:v',
    '800k',
    '-r',
    '30',
    '-'
  ]
}

```

Steps:
- git clone in windows
- cd the project and run npm install -g
- edit app.js by uncommenting last one example
- node app.js

**Comment by revolucionx2** [comment]
you have to install ffmpeg
